### ISSUE TITLE
Rewording the "Daily Presence" 

### ISSUE THREAD

**Issue by dmannan** [neurodata/about#2]
Under the "Daily Presence" section, the following sentence is misleading: 

> We agree to be around the lab many working hours each day (which we define for convenience at 10am to 5pm on days that school is open, irrespective of class schedule).

"irrespective of class schedule" can be interpreted as being present in the lab, even if the student has conflicting class schedule. I suggest the sentence be reworded to: "...(which we define for convenience at 10am to 5pm, irrespective of JHU academic calendar).

**Comment by jovo** [comment]
Make a PR
