### ISSUE TITLE
agreements & asana

### ISSUE THREAD

**Issue by falkben** [neurodata/about#5]
In https://github.com/neurodata/about/blob/master/agreements.md we have:

>No late tasks on asana, ever.

I have not been meeting this obligation.  It's not clear to me that anyone else is either -- at least not for "products" (for lack of a better word).  There are probably many reasons for this -- projects are hard to scope, things change, updating asana is a chore...

This also isn't in line with how I've been using Asana (which is maybe my mistake).  I have been using it for project organization and less so for defining my commitments.  There are also no consequences for not meeting this obligation.  I wonder if we should revise this?  My suggestion would be to something less severe -- "Strive for no late tasks on asana". Or, instead, change how we use Asana (as a group)?

**Comment by jovo** [comment]
agreed, i changed it. i think better now?
re-open if you still don't like it.
